### ISSUE TITLE
Crash when compiling quickhull with the hybrid-sched-decentralize branch

### ISSUE THREAD

**Issue by athas** [MPLLang/mpl#179]
Compiling [this program](https://github.com/MPLLang/parallel-ml-bench/tree/main/mpl/bench/quickhull) with the command

    mpl -mlb-path-var 'COMPAT mpl' pure-quickhull.mlb

fails with the error

```
MLton [mpl] ???????? raised: Fail: SplitTypes.transform.conTycon: dummy_0 in val global_0: choice_status_0 = con dummy_0 in Globals
```

This does not happen when using the `master` branch.

**Comment by MatthewFluet** [comment]
The `hybrid-sched-decentralize` branch must have branched before ba59f033.

**Comment by shwestrick** [comment]
I've been compiling with `-disable-pass splitTypes1 -disable-pass splitTypes2` on this branch for now.

**Comment by shwestrick** [comment]
Closing this now; as of 2bf43c8 both `splitTypes1` and `splitTypes2` are disabled by default in branch `hybrid-sched`
