### ISSUE TITLE
Inlining tail calls as loops on spork branch

### ISSUE THREAD

**Issue by colin-mcd** [MPLLang/mpl#203]
[This commit](https://github.com/MPLLang/mpl/commit/48715fa3d4bd177d66d1be60854641680ea798e3) inlines tail-recursive calls nested within other inlined function bodies as flat goto-loops. However, this should only happen if _all_ calls between the originally inlined function and the tail-rec call are tail returns. I'll work on a quick fix.

Correct example:
```sml
fun a_loop (i, j, acc) =
  if i >= j then acc else b_loop (i + 1, j, acc + i)
fun b_loop (i, j, acc) =
  if i >= j then acc else b_loop (i, j - 1, acc + j)
```
becomes
```
block a_loop(i, j, acc) =
   ...
   goto b_loop(i, j', acc')
block b_loop(i, j, acc) =
  ...
  goto a_loop(i', j, acc')
```

However, consider for example
```sml
fun break_tail_return x =
  1 + x
fun make_tail_returnf x =
  f x
fun a_loop (i, j, acc) =
  if i >= j then acc else break_tail_return (make_tail_return b_loop (i + 1, j, acc + i))
fun b_loop (i, j, acc) =
  if i >= j then acc else b_loop (i, j - 1, acc + j)
```
Where because `make_tail_return` returns `f` as tail, inlining will improperly have it `goto` the loop block for `b_loop` when it must actually be a call because it will otherwise discard the return continuation `break_tail_return`.

**Comment by MatthewFluet** [comment]
I don't understand how this is breaking in the inlining transformation.  We compute the "return context" of a potentially inlined call at:
https://github.com/MPLLang/mpl/blob/48715fa3d4bd177d66d1be60854641680ea798e3/mlton/ssa/inline.fun#L441
This should account for any outer non-tail call that was inlined.  Then, we only transform the `Call` to a `Goto` if that composed return context is `Tail`:
https://github.com/MPLLang/mpl/blob/48715fa3d4bd177d66d1be60854641680ea798e3/mlton/ssa/inline.fun#L478-L487

**Comment by colin-mcd** [comment]
Ohh you're right! Oops sorry, I should've tested that this actually is an issue first :P

**Comment by MatthewFluet** [comment]
Oh, good.  I thought that you had an example program that was breaking.

**Comment by colin-mcd** [comment]
Although, could we perhaps be missing some opportunities if the whole composed return is nontail, but say the last 5 returns are tail and there is a rec tail call of one of the 5 most recently inlined functions?

**Comment by MatthewFluet** [comment]
Yes, I was just reflecting on exactly the same thing.

**Comment by MatthewFluet** [comment]
You are correct that a "looping" function (e.g., that has not yet been turned into a loop, either because the `IntroduceLoops` pass has not yet been run or because some to-be-inlined wrapper is obfuscating the call) could in inlined in a non-tail position, but we would still like to "close the loop".

Perhaps we should change:
```sml
and doit (blocks: Block.t vector,
                return: Return.t,
                newBlocks: Block.t vector,
                nest: (Func.t * Label.t) list) : Block.t vector =
```
to
```sml
and doit (blocks: Block.t vector,
                newBlocks: Block.t vector,
                nest: (Func.t * Label.t * Return.t) list) : Block.t vector =
```
If it is all `Return.Tail` from the `Call` through `nest` to the `Func.t`, then we can `Goto`.

Otherwise, we need to compute the composed `Return.t` for other inlining.
