### ISSUE TITLE
Assertion failures on interactive-merge

### ISSUE THREAD

**Issue by smuller** [MPLLang/mpl#71]
I get one of the following assertion failures when I compile with -debug true -debug-runtime true and run on more than one processor:
fib_term-new: gc/object.c:64: splitHeader: Assertion `1 == (header & GC_VALID_HEADER_MASK)' failed.

fib_term-new: gc/foreach.c:280: foreachObjptrInRange: Assertion `isAligned ((size_t)front, GC_MODEL_MINALIGN)' failed.

**Comment by shwestrick** [comment]
I'm closing this because MPL has diverged so much from the old mlton-parmem. Maybe one day we'll finally get around to integrating Stefan's work into MPL 😃
